<?php

/**
 * Implements hook_token_info().
 */
function htt_token_info() {
  $info['tokens']['node']['node_category'] = array(
    'name' => t('Site category'),
    'description' => t(''),
  );
  return $info;
}

/**
 * Implements hook_tokens().
 */
function htt_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  $replacements['[node:node_category]'] = "";
  if(!isset($data['entity']) || $data['entity'] == null || $data['entity']->getEntityTypeId() != 'node') {return;}
  /*if($data['entity']-> getType() == 'novost')
  {
    return;
  }*/
  if(!$data['entity']->hasField('field_site_category'))
  {
    return;
  }
  $tid = $data['entity']->get('field_site_category')->getValue()[0]['target_id'];
  $parents_list[$tid] = array();
  $term_storage = \Drupal::entityManager()->getStorage('taxonomy_term');
  $parents = $term_storage->loadAllParents($tid);
  // Remove this term from the array.
  if(count($parents)>1){array_shift($parents);}
  $parents = array_reverse($parents);
  foreach ($parents as $term) {
    $parents_list[$tid][$term->id()] = $term->label();
  }
  $string = implode("/",array_shift($parents_list));
  $replacements['[node:node_category]'] = $string;
  return $replacements;
}

//Транслитерация
function GetInTranslit($string) {
  $replace=array(
    "'"=>"",
    "`"=>"",
    " "=>"-",
    "а"=>"a","А"=>"a",
    "б"=>"b","Б"=>"b",
    "в"=>"v","В"=>"v",
    "г"=>"g","Г"=>"g",
    "д"=>"d","Д"=>"d",
    "е"=>"e","Е"=>"e",
    "ж"=>"zh","Ж"=>"zh",
    "з"=>"z","З"=>"z",
    "и"=>"i","И"=>"i",
    "й"=>"y","Й"=>"y",
    "к"=>"k","К"=>"k",
    "л"=>"l","Л"=>"l",
    "м"=>"m","М"=>"m",
    "н"=>"n","Н"=>"n",
    "о"=>"o","О"=>"o",
    "п"=>"p","П"=>"p",
    "р"=>"r","Р"=>"r",
    "с"=>"s","С"=>"s",
    "т"=>"t","Т"=>"t",
    "у"=>"u","У"=>"u",
    "ф"=>"f","Ф"=>"f",
    "х"=>"h","Х"=>"h",
    "ц"=>"c","Ц"=>"c",
    "ч"=>"ch","Ч"=>"ch",
    "ш"=>"sh","Ш"=>"sh",
    "щ"=>"sch","Щ"=>"sch",
    "ъ"=>"","Ъ"=>"",
    "ы"=>"y","Ы"=>"y",
    "ь"=>"","Ь"=>"",
    "э"=>"e","Э"=>"e",
    "ю"=>"yu","Ю"=>"yu",
    "я"=>"ya","Я"=>"ya",
    "і"=>"i","І"=>"i",
    "ї"=>"yi","Ї"=>"yi",
    "є"=>"e","Є"=>"e"
  );
  return $str=iconv("UTF-8","UTF-8//IGNORE",strtr($string,$replace));
}